#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    binName=$(basename $0)
    echo "usage: $binName <user_name> [newpassword]"
    exit 0
}

# ask #
function ask_yes_or_no() {
   read -p "$1 ([y]es or [N]o): "
   case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
      y|yes) echo "yes" ;;
      *)     echo "no" ;;
   esac
}

# one arg, the username #
if [ $# -eq 0 ] || [ $# -gt 2 ]; then
    usage
fi

user=$1
password=$2

# check if the user exit #
if ! wbinfo -i $user > /dev/null 2>&1; then
   echo "The user $user does not exist !"
   exit 0
fi


###################
# change password #
###################
if [ -z "$password" ]; then
   if [ $(ask_yes_or_no "Would you like to reset the password of the user $user ?") == "yes" ]; then
      samba-tool user setpassword $user --newpassword=$user
   fi
else
   if [ $(ask_yes_or_no "Would you like to set the ${user}'s password to $password ?") == "yes" ]; then
      samba-tool user setpassword $user --newpassword=$password
   fi
fi
