#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    binName=$(basename $0)
    echo "usage: $binName [class_name] [-g class_group] [-n class_show_name]"
    exit 1
}


###########
#parse args
###########
while [[ -n "$@" ]]; do

    # test option #
    OPTIND=1
    while getopts ":hg:n:" opt; do
	case $opt in
	    g)
		classGroup=$OPTARG
		;;
            n)
                classShowName=$OPTARG
                ;;
	    h)
		usage
		;;
	    \?)
		echo "option -$OPTARG not recognized !"
		usage
		;;
	    :)
		echo "parameter of -$OPTARG not specified !"
		exit 1
		;;
	esac
    done

    # check classic args #
    if [ $OPTIND != 1 ]; then
       shift $((OPTIND-1))
    else
       remArgs="$remArgs $1"
       shift 1
    fi
done

# reset args #
if [ -n "$remArgs" ]; then
    set $remArgs
fi


#################
# analyse args
#################

# max one args #
if [ $# -gt 1 ]; then
    usage
fi

# get class name #
className="$1"

# check the class group #
if [ ! -z "$classGroup" ]; then
   classGroup=${classGroup,,}
   if [ ! -z "$className" ]; then
      if [ "${className,,}" != "$classGroup" ]; then
         echo "Error : The class group must be the class name in lowercase !"
         exit 1
      fi
   fi
fi

########################
# find the class group #
########################

# get the group name if possible
if [ ! -z "$className" ]; then
   classGroup=${className,,}
fi

# build search cond #
if [ ! -z "$classGroup" ]; then
   searchCond="(cn=$classGroup)"
fi

if [ ! -z "$classShowName" ]; then
   if [ -z "$searchCond" ]; then
      searchCond="(displayName=$classShowName)"
   else
      searchCond="(&${searchCond}(displayName=$classShowName))"
   fi
fi

# check search cond #
if [ -z "$searchCond" ]; then

   # no condition given #
   usage
fi

# search #
searchClass=$(s4ldbsearch $baseUserDN,$baseDN sub group $searchCond)
if [ "$?" -ne "0" ]; then
   echo "No class found !"
   exit 1
else
   resultCount=$(echo "$searchClass" | wc -l)
   if [ "$resultCount" -ne "1" ]; then
      echo "Multiple classes found !"
      exit 1
   fi
fi

# rebuild the class name/group if needed #
if [ -z "$className" ]; then

   # read the class name  #
   # the OU containing the group #
   className=$(echo "$searchClass" | cut -d, -f2)
   className=${className#OU=}
   classGroup=${className,,}
fi


######################
# check the share dn #
######################

# check the corresponding share OU #
classDN=${searchClass#CN=$classGroup,}
classDN=${classDN%,$baseDN}
classShareDN=${classDN%$baseUserDN}
classShareDN="${classShareDN}$baseShareDN"

searchClass=$(s4ldbsearch $classShareDN,$baseDN base ou '()')
if [ "$?" -ne "0" ]; then
   echo "Cannot find the share OU of the class $className ! Maybe not a class group."
   exit 1
fi

echo "Class Name: $className"
echo "Class group: $classGroup"
echo "Class DN: $classDN"
echo "Class share DN: $classShareDN"

exit 0
