#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    binName=$(basename $0)
    echo "usage: $binName <class_name> [-b base_class] [-d display_name]"
    exit 0
}

###########
#parse args
###########
while [[ -n "$@" ]]; do

    # test option #
    OPTIND=1
    while getopts ":hb:d:" opt; do
        case $opt in
            b)
                baseClass=$OPTARG
                ;;
            d)
                classDisplayName=$OPTARG
                ;;
            h)
                usage
                ;;
            \?)
                echo "option -$OPTARG not recognized !"
                usage
                ;;
            :)
                echo "parameter of -$OPTARG not specified !"
                exit 0
                ;;
        esac
    done

    # check classic args #
    if [ $OPTIND != 1 ]; then
       shift $((OPTIND-1))
    else
       remArgs="$remArgs $1"
       shift 1
    fi
done

# reset args #
if [ -n "$remArgs" ]; then
    set $remArgs
fi;

#################
# analyse args
#################

# one arg, the class #
if [ $# != 1 ]; then
    usage
fi

className=$1
classGroup=${1,,}

# check the base class #
if [ -z "$baseClass" ]; then
   baseClassGroup=${baseUserGroup}
   baseClassDN=''
else
   baseClassName=${baseClass}
   if ! baseClassInfo=$(s4classcheck $baseClassName); then
      echo "The base class $baseClassName cannot be found !"
      exit 1
   else
      baseClassGroup=$(echo "$baseClassInfo" | grep 'Class group: ')
      baseClassGroup=${baseClassGroup#Class group: }
      baseClassDN=$(echo "$baseClassInfo" | grep 'Class DN: ')
      baseClassDN=${baseClassDN#Class DN: }
      baseClassDN=${baseClassDN%${baseUserDN}}
   fi
fi

# check display name #
if [ -z "$classDisplayName" ]; then
   classDisplayName=$className
fi

###################
# create the class
###################

# check if the class already exist or the group already used #
if s4ldbsearch $baseDN sub group "(cn=$classGroup)" > /dev/null; then
   echo "The class $className or the group $classGroup already exist !"
   exit 1
fi

# create the organizational unit #
# ${baseClassDN} can be empty #
echo "create $className organizational units."
samba-tool ou create "OU=${className},${baseClassDN}${baseUserDN},${baseDN}"
samba-tool ou create "OU=${className},${baseClassDN}${baseShareDN},${baseDN}"

# create the groups #
s4groupadd $classGroup -d OU=${className},${baseClassDN}${baseUserDN}

echo "dn: CN=$classGroup,OU=${className},${baseClassDN}${baseUserDN},${baseDN}
changetype: modify
add: displayName
displayName: $classDisplayName" > /tmp/$className

ldbmodify --url=$samDatabase -b $baseDN /tmp/$className
rm /tmp/$className
