#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    binName=$(basename $0)
    echo "usage: $binName <group_name>"
    exit 0
}


###########
#parse args
###########
while [[ -n "$@" ]]; do

    # test option #
    OPTIND=1
    while getopts ":h" opt; do
	case $opt in
	    h)
		usage
		;;
	    \?)
		echo "option -$OPTARG not recognized !"
		usage
		;;
	    :)
		echo "parameter of -$OPTARG not specified !"
		exit 0
		;;
	esac
    done

    # check classic args #
    if [ $OPTIND != 1 ]; then
       shift $((OPTIND-1))
    else
       remArgs="$remArgs $1"
       shift 1
    fi
done

# reset args #
if [ -n "$remArgs" ]; then
    set $remArgs
fi;


#################
# analyse args
#################

# one arg, the group #
if [ $# != 1 ]; then
    usage
fi

groupName=$1

# check if the group already exit #
if ! wbinfo --group-info $groupName > /dev/null 2>&1; then
   echo "The group $groupName don't exist !"
   exit 1
fi

# check if the group belong to a class #
if classInfo=$(s4classcheck -g $groupName); then
   className=$(echo "$classInfo" | grep 'Class Name: ')
   className=${className#Class Name: }
   echo "The group $groupName belong to the class $className !"
   echo "To delete the group, you need to delete the class with :"
   echo "s4classdel $className"
   exit 0
fi


####################
# delete the group #
####################
samba-tool group delete $groupName

echo "Group $groupName deleted !"
