#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    binName=$(basename $0)
    echo "usage: $binName"
    exit 0
}

function ask_yes_or_no() {
   read -p "$1 ([y]es or [N]o): "
   case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
      y|yes) echo "yes" ;;
      *)     echo "no" ;;
   esac
}


#################
# analyse args
#################

# no args #
if [ $# -ne 0 ]; then
    usage
fi


###########################
# Create school structure #
###########################

if [ $(ask_yes_or_no "Would you like to create a base school structure ?") == "no" ]; then
   exit 0
fi


# get class names #
usersClassName=${baseUserDN#OU=}
teachersClassName=${baseTeacherDN#OU=}
teachersClassName=${teachersClassName%,OU=$usersClassName}
studentsClassName=${baseStudentDN#OU=}
studentsClassName=${studentsClassName%,OU=$usersClassName}

# create Teacher class #
s4classadd $teachersClassName -d $baseTeacherDir

# create Student class #
s4classadd $studentsClassName -d $baseStudentDir

# create Teacher share #
s4shareadd ${teachersDirName,,} $teachersClassName 770 -n $teachersDirName
