#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    echo "usage: $0"
    exit 0
}


#################
# analyse args
#################

# no args #
if [ $# -ne 0 ]; then
    usage
fi


###########################
# Create school structure #
###########################

# get class names #
usersClassName=${baseUserDN#OU=}
teachersClassName=${baseTeacherDN#OU=}
teachersClassName=${teachersClassName%,OU=$usersClassName}
studentsClassName=${baseStudentDN#OU=}
studentsClassName=${studentsClassName%,OU=$usersClassName}

# create Teacher class #
s4classadd $teachersClassName -d $baseTeacherDir

# create Student class #
s4classadd $studentsClassName -d $baseStudentDir

# create Teacher share #
s4shareadd ${teachersDirName,,} 770 $teachersClassName -n $teachersDirName
