#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    binName=$(basename $0)
    echo "usage: $binName <share_name>"
    exit 1
}


###########
#parse args
###########
while [[ -n "$@" ]]; do

    # test option #
    OPTIND=1
    while getopts ":h" opt; do
	case $opt in
	    o)
		shareOwner=$OPTARG
		;;
            n)
                shareShowName=$OPTARG
                ;;
            s)
                shareServer=$OPTARG
                ;;
	    h)
		usage
		;;
	    \?)
		echo "option -$OPTARG not recognized !"
		usage
		;;
	    :)
		echo "parameter of -$OPTARG not specified !"
		exit 1
		;;
	esac
    done

    # check classic args #
    if [ $OPTIND != 1 ]; then
       shift $((OPTIND-1))
    else
       remArgs="$remArgs $1"
       shift 1
    fi
done

# reset args #
if [ -n "$remArgs" ]; then
    set $remArgs
fi


#################
# analyse args
#################

#-------------------#
# check args number #
#-------------------#

# one arg, the share #
if [ $# -ne 1 ]; then
    usage
fi

shareName=$1

# check that the user is a share #
if ! s4ldbsearch $baseShareDN,$baseDN sub user "(cn=$shareName)" > /dev/null; then
   echo "Cannot find the share $shareName !"
   exit 0
fi

####################
# delete the share #
####################
samba-tool user delete $shareName
echo "Share $shareName deleted !"

echo "##################################################"
echo "# !!! Launch s4makeshareddirs on the servers !!! #"
echo "# !!! to update the network shares.          !!! #"
echo "##################################################"
