#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    binName=$(basename $0)
    echo "usage: $binName <class_name>"
    exit 0
}


#################
# analyse args
#################

# one arg, the class #
if [ $# -ne 1 ]; then
    usage
fi

newStudentClassName=$1
newStudentClassGroup=${1,,}

########################
# create student class #
########################

# get class names #
usersClassName=${baseUserDN#OU=}
teachersClassName=${baseTeacherDN#OU=}
teachersClassName=${teachersClassName%,OU=$usersClassName}
studentsClassName=${baseStudentDN#OU=}
studentsClassName=${studentsClassName%,OU=$usersClassName}
teachersGroupName=${teachersClassName,,}
studentsGroupName=${studentsClassName,,}

# create the class #
s4classadd $newStudentClassName -b $studentsClassName

# if already exist, stop #
if [ "$?" -ne "0" ]; then
   exit 1
fi

#####################
# create the shares #
#####################

# create resource share
s4shareadd ${resourceDirName,,} $newStudentClassName:$teachersClassName 1750,g:$teachersGroupName:rwx -n $resourceDirName

#create shared share
s4shareadd ${sharedDirName,,} $newStudentClassName:$teachersClassName g:$newStudentClassGroup:rwx,g:$teachersGroupName:rwx,d:u::rwx,d:g::r-x,d:g:$teachersGroupName:rwx -n $sharedDirName

#create test folder
s4shareadd ${testDirName,,} $newStudentClassName:$teachersClassName g:$newStudentClassGroup:rwx,g:$teachersGroupName:rwx,d:u::rwx,d:g::---,d:g:$newStudentClassGroup:---,d:o::---,d:g:$teachersGroupName:rwx -n $testDirName
