#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    echo "usage: $0 <student_name> <target_class>"
    exit 0
}


###########
#parse args
###########
while [[ -n "$@" ]]; do

    # test option #
    OPTIND=1
    while getopts ":h" opt; do
	case $opt in
	    h)
		usage
		;;
	    \?)
		echo "option -$OPTARG not recognized !"
		usage
		;;
	    :)
		echo "parameter of -$OPTARG not specified !"
		exit 0
		;;
	esac
    done

    # check classic args #
    if [ $OPTIND != 1 ]; then
       shift $((OPTIND-1))
    else
       remArgs="$remArgs $1"
       shift 1
    fi
done

# reset args #
if [ -n "$remArgs" ]; then
    set $remArgs
fi


#################
# analyse args
#################

# need two args #
if [ $# -ne 2 ]; then
    usage
fi

# parse username #
studentName=$1

# check if the student account exist #
# already done in s4usermove #

# check if the account is a student #
searchStudent=$(s4ldbsearch -H $samDatabase -b $baseStudentDN,$baseDN "(cn=$studentName)" | grep "dn: CN=$studentName,OU=.*,$baseStudentDN")
if [ -z "$searchStudent" ]; then
   echo "The user $studentName is not a student !"
   exit 0
fi

# check if the target class is a student's class #
studentTargetClassName=$2
studentTargetClassGroup=${2,,}

searchClass=$(s4ldbsearch -H $samDatabase -b $baseStudentDN,$baseDN "(cn=$studentTargetClassGroup)" | grep "dn: CN=$studentTargetClassGroup,OU=$studentTargetClassName,$baseStudentDN")
if [ -z "$searchClass" ]; then
   echo "The class $studentTargetClassName is not a student's class !"
   exit 0
fi

####################
# move the student #
####################

s4usermove $studentName $studentTargetClassName


