#!/bin/bash

##############
#base var
##############
source /etc/samba/s4.conf

# usage #
function usage()
{
    binName=$(basename $0)
    echo "usage: $binName <student_name> <target_class>"
    exit 0
}


###########
#parse args
###########
while [[ -n "$@" ]]; do

    # test option #
    OPTIND=1
    while getopts ":h" opt; do
	case $opt in
	    h)
		usage
		;;
	    \?)
		echo "option -$OPTARG not recognized !"
		usage
		;;
	    :)
		echo "parameter of -$OPTARG not specified !"
		exit 0
		;;
	esac
    done

    # check classic args #
    if [ $OPTIND != 1 ]; then
       shift $((OPTIND-1))
    else
       remArgs="$remArgs $1"
       shift 1
    fi
done

# reset args #
if [ -n "$remArgs" ]; then
    set $remArgs
fi


#################
# analyse args
#################

# need two args #
if [ $# -ne 2 ]; then
    usage
fi

# parse username #
studentName=$1
studentTargetClassName=$2

# check if the account is a student #
if ! s4ldbsearch $baseStudentDN,$baseDN sub user "(cn=$studentName)" > /dev/null; then
   echo "The user $studentName is not a student !"
   exit 1
fi

# check if the class exist #
if ! studentTargetClassInfo=$(s4classcheck $studentTargetClassName); then
   echo "The class $studentTargetClassName cannot be found !"
   exit 1
fi

# check if the target class is a student's class #
studentTargetClassDN=$(echo "$studentTargetClassInfo" | grep '^Class DN: ')
studentTargetClassDN=${studentTargetClassDN#Class DN: }
if ! echo "$studentTargetClassDN" | grep -q "$baseStudentDN\$"; then
   echo "The student class $studentTargetClassName is not a student class !"
   exit 1
fi

####################
# move the student #
####################

s4usermove $studentName $studentTargetClassName
