#!/bin/bash

#--------------------------------------------------------#
#                                                        #
# migrate users present in :                             #
# /var/cache/accountserver/users_waiting_migration.list  #
#                                                        #
# and shares present in :                                #
# /var/cache/accountserver/shares_waiting_migration.list #
#                                                        #
#--------------------------------------------------------#


#####################
# migrate the users #
#####################
s4usermigrate -n -u

######################
# migrate the shares #
######################
s4sharemigrate -n -u
