#!/bin/bash

#--------------------------------------------------------#
#                                                        #
# migrate users present in :                             #
# /var/cache/accountserver/users_waiting_migration.list  #
#                                                        #
#--------------------------------------------------------#

waitingFile='/var/cache/accountserver/users_waiting_migration.list'

# get all current waiting users #
waitingUsers=$(cat $waitingFile);

# try to migrate all users #
while read line; do

   # get params #
   user=$(echo "$line" | cut -d ' ' -f1)
   server=$(echo "$line" | cut -d ' ' -f2)

   # check #
   if [ ! -z "$user" ] && [ ! -z "$server" ]; then

      # migrate #
      echo "s4usermigrate -n $user $server > /dev/null 2>&1"

      # if successfull remove from the list #
      if [ "$?" -eq "0" ]; then
         sed -i "/$line/d" "$waitingFile"
      fi
   fi
done <<< "$waitingUsers"
